config/routes.rb
Rails.application.routes.draw do
	root to: 'visitors#index'
	get 'users/:id/edit_user', to: 'users#edit_user'

	# latter half of next line overrides devise registrations, using mine instead
	#devise_for :users, :controllers => {:registrations => "registrations"}
	devise_for :users, :controllers => {:registrations => "users"}

	resources :users, :controller => 'users'


end

app/models/user.rb
class User < ActiveRecord::Base
	enum role: [:user, :vip, :admin]
	after_initialize :set_default_role, :if => :new_record?

	def set_default_role
		self.role ||= :user
	end

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable

	belongs_to :vendor, :class_name => 'Vendor', :foreign_key => :vendor_id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  prepend_before_action :require_no_authentication, only: [:cancel]
  prepend_before_action :authenticate_scope!, only: [:edit, :update, :destroy]

  # no registration actions unless you are an admin
  before_action :admin_only

  def index
    puts "--------- index"
    puts current_user.vendor_id
    @users = User.where(vendor_id: current_user.vendor_id)
    @user = current_user.name
    puts @user
  end

  def add_user
    @user = User.find_by_id_and_vendor_id(params[:id], current_user.vendor_id)
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def edit_user
    puts "======= edit user. params #{params[:id]}"
    @user = User.find(params[:id])
    puts "user : #{@user.id} , #{@user.name}"
    puts @user.name
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def new
    puts "======== new, param = #{params[:id]}"
    @user = current_user
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end


  def show
    puts "--------- user show"
    @user = current_user
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    puts "--------- update"
    @user = User.find_by_id_and_vendor_id(params[:id], current_user.vendor_id)
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def create
    puts " ========= create"
    resource = User.new()
    resource.name = params[:user][:name]
    resource.email = params[:user][:email]
    resource.password = params[:user][:password]
    resource.password_confirmation = params[:user][:password_confirmation]
    resource.vendor_id = current_user.vendor_id

    resource.save
    yield resource if block_given?
    if resource.persisted?
      flash[:notice] = "User succesfully signed up"
      redirect_to "/users"
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to "/users"
    end
  end

  def destroy
    puts "--------- destroy"
    #user = User.find(params[:id])
    user = User.find_by_id_and_vendor_id(params[:id], current_user.vendor_id)

    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end



  private

  def admin_only
    puts "--------- admin_only"
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end



end

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>

	<%= link_to("Edit", user_path(user) + '/edit_user', :class => 'button-xs') unless user == current_user %>

<td>
  <%= link_to("Delete", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/add_user.erb
<div class="authform">
  <%= form_for @user, url: users_index_path(@user)  do |f| %> 
    <h3>Create User foo</h3>
    <%= devise_error_messages! %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
     <%= f.submit 'Kill', :class => 'button right' %>
  <% end %>
</div>

app/views/users/edit_user.erb
<div class="authform">
  <%= form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :put }) do |f| %>
    <h3>Change password for <%= @user.name%></h3>
    <%= devise_error_messages! %>
    <%= f.hidden_field :reset_password_token %>
    <div class="form-group">
      <%= f.label :password, 'New password' %>
        <%= f.password_field :password, autofocus: true, autocomplete: 'off', class: 'form-control' %>
      <%= f.label :password_confirmation, 'Confirm new password' %>
        <%= f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control' %>
    </div>
     <%= f.submit 'Change my Password', :class => 'button right' %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
      <h3>Users</h3>
      <%= link_to("Add User", "users/sign_up", :method => :get, :class => 'button-xs') %>
    </div>
  <div class="row" id="in_user_table">
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.erb
<div class="authform">
  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :role => 'form'}) do |f| %>
    <h3>Sign up</h3>
    <%= devise_error_messages! %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
     <%= f.submit 'Sign up', :class => 'button right' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>